tap "d12frosted/emacs-plus"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
brew "d12frosted/emacs-plus/emacs-plus"
brew "cask", args: ["ignore-dependencies"]
brew "hunspell"
brew "python"
cask "db-browser-for-sqlite"
cask "font-anonymous-pro"
cask "font-anonymouspro-nerd-font"
cask "hammerspoon"
cask "iterm2"
cask "qlmarkdown"
cask "spotify"
cask "vlc"
